name: "Publish"

on:
  push:
    branches:
      - "master"
jobs:
  bump-version:
    name: "Publish from master"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'ci: version bump to ')"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
      - name: "Setup Node"
        uses: "actions/setup-node@v2"
        with:
          node-version: 16
      - name: Update NPM
        run: npm install -g npm
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm publish --access public
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
